### PR TITLE
PAS217: Cannot authenticate with security key

### PR DESCRIPTION
**Pull request by jonashendrickx**
We should be either passing null, and leave the decision elsewhere, or default to 'preferred'.

https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/get

> {
>   "method": "navigator.credentials.create",
>   "options": {
>     "publicKey": {
>       "rp": {
>         "id": "localhost",
>         "name": "localhost"
>       },
>       "user": {
>         "name": "Playground: user1@example.com",
>         "id": "ZjkzZTc4ZTQtNDIyMS00ZWQ3LTg3N2EtMjZlMjgwZDM3ODhk",
>         "displayName": "User 1"
>       },
>       "challenge": "xpJEaV1/3TCOHz3Vji/HcQ==",
>       "pubKeyCredParams": [
>         {
>           "type": "public-key",
>           "alg": "EdDSA"
>         },
>         {
>           "type": "public-key",
>           "alg": "ES256"
>         },
>         {
>           "type": "public-key",
>           "alg": "RS256"
>         },
>         {
>           "type": "public-key",
>           "alg": "PS256"
>         },
>         {
>           "type": "public-key",
>           "alg": "ES384"
>         },
>         {
>           "type": "public-key",
>           "alg": "RS384"
>         },
>         {
>           "type": "public-key",
>           "alg": "PS384"
>         },
>         {
>           "type": "public-key",
>           "alg": "ES512"
>         },
>         {
>           "type": "public-key",
>           "alg": "RS512"
>         },
>         {
>           "type": "public-key",
>           "alg": "PS512"
>         }
>       ],
>       "timeout": 60000,
>       "attestation": "none",
>       "authenticatorSelection": {
>         "residentKey": "required",
>         "requireResidentKey": true,
>         "userVerification": "preferred"
>       },
>       "excludeCredentials": [],
>       "extensions": {
>         "credProps": true
>       },
>       "status": "ok",
>       "errorMessage": ""
>     }
>   },
>   "response": {
>     "value": {
>       "authenticatorAttachment": "cross-platform",
>       "getClientExtensionResults": {
>         "credProps": {
>           "rk": true
>         }
>       },
>       "id": "2cmWR9rsJ8ttpI3RZ4XG1uRhyN8FUDwQbsmvCp9zAz5FGj5EbtXNl9qH6uJpGiIL",
>       "rawId": "2cmWR9rsJ8ttpI3RZ4XG1uRhyN8FUDwQbsmvCp9zAz5FGj5EbtXNl9qH6uJpGiIL",
>       "type": "public-key",
>       "response": {
>         "attestationObject": {
>           "fmt": "none",
>           "attStmt": {},
>           "authData": {
>             "rpIdHash": "49960de5880e8c687434170f6476605b8fe4aeb9a28632c7995cf3ba831d9763",
>             "flags": {
>               "userPresence": true,
>               "reserved1": false,
>               "userVerification": true,
>               "backupEligibility": false,
>               "backupState": false,
>               "reserved2": false,
>               "attestationData": true,
>               "extensionData": true
>             },
>             "counter": 1,
>             "attestedCredentialData": {
>               "aaguid": "00000000-0000-0000-0000-000000000000",
>               "credentialIdLength": 48,
>               "credentialId": "d9c99647daec27cb6da48dd16785c6d6e461c8df05503c106ec9af0a9f73033e451a3e446ed5cd97da87eae2691a220b",
>               "credentialPublicKey": {
>                 "1": 1,
>                 "3": -8,
>                 "-1": 6,
>                 "-2": "d9c99647daec27cb6da48dd167ac7fbb47fd6c56b61a954a1bc4cd2e8eaa2267"
>               }
>             },
>             **"extensionData": {
>               "credProtect": 3
>             }**
>           }
>         },
>         "clientDataJSON": {
>           "type": "webauthn.create",
>           "challenge": "xpJEaV1_3TCOHz3Vji_HcQ",
>           "origin": "https://localhost:8002",
>           "crossOrigin": false
>         },
>         "getAuthenticatorData": {
>           "rpIdHash": "49960de5880e8c687434170f6476605b8fe4aeb9a28632c7995cf3ba831d9763",
>           "flags": {
>             "userPresence": true,
>             "reserved1": false,
>             "userVerification": true,
>             "backupEligibility": false,
>             "backupState": false,
>             "reserved2": false,
>             "attestationData": true,
>             "extensionData": true
>           },
>           "counter": 1,
>           "attestedCredentialData": {
>             "aaguid": "00000000-0000-0000-0000-000000000000",
>             "credentialIdLength": 48,
>             "credentialId": "d9c99647daec27cb6da48dd16785c6d6e461c8df05503c106ec9af0a9f73033e451a3e446ed5cd97da87eae2691a220b",
>             "credentialPublicKey": {
>               "1": 1,
>               "3": -8,
>               "-1": 6,
>               "-2": "d9c99647daec27cb6da48dd167ac7fbb47fd6c56b61a954a1bc4cd2e8eaa2267"
>             }
>           },
>           **"extensionData": {
>             "credProtect": 3
>           }**
>         },
>         "getPublicKey": "302a300506032b6570032100d9c99647daec27cb6da48dd167ac7fbb47fd6c56b61a954a1bc4cd2e8eaa2267",
>         "getPublicKeyAlgorithm": "EdDSA",
>         "getTransports": [
>           "nfc",
>           "usb"
>         ]
>       }
>     }
>   }
> }

### CODE REVIEW

**Comment by jrmccannon** [comment]
We should probably include this in release notes. It could break things for current users.

**Comment by jonashendrickx** [comment]
> We should probably include this in release notes. It could break things for current users.

Nah it doesn't break things. We were passing discouraged to navigator.credentials.get, but since the yubikey requires user verification, it would fail to log you in. It shouldn't have any impact. The spec defines to either leave it as null or set to preferred

**Review by jrmccannon — APPROVED** [review]

**Comment by abergs** [comment]
Hm, I'm not 100% convinced of this change. Discouraged is there to enable the smoothest sign in flow with least friction, which I think is a reasonable default for us.

Yubijeys *should* support accepting the option, but may choose to not do UV. I'm curious what fails that auth.

**Review by abergs — CHANGES_REQUESTED** [review]
Just holding this PR until we've discussed more :)

**Comment by jonashendrickx** [comment]
> Just holding this PR until we've discussed more :)

For clarity, when registering a credential with userVerification set to preferred, the authenticator is returning a response with credProtect of value 3, effectively requiring userVerification. When we sign in with userVerification discouraged, the authenticator would abort during the signin process.

userVerification discouraged would result in a credProtect value of 2.

Tested with YubiKey 5C using firmware 5.4.3.

**Review by abergs — APPROVED** [review]

**Pull request merged**
