### PR TITLE
PAS-194: Rename `AuditLog` -> `EventLog`

### PR DESCRIPTION
**Pull request by Tyrrrz**

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Should I also update database symbols to match? @jrmccannon @abergs

**Comment by abergs** [comment]
@jrmccannon @Tyrrrz  I think so?

**Comment by jrmccannon** [comment]
Probably best.

**Comment by Tyrrrz** [comment]
@jonashendrickx Let me know when it is

**Review by jrmccannon — APPROVED** [review]

**Pull request merged**
